# Generated by Django 5.2.3 on 2026-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('management', 'Management')], default='student', max_length=20),
        ),
    ]
