# Generated by Django 5.2.3 on 2026-06-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_track', '0005_student_dob_student_father_name_student_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='temp001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
