# Generated by Django 5.2.3 on 2026-08-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_track', '0006_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('parents', 'Parents')], default='student', max_length=20),
        ),
    ]
