# Generated by Django 5.2.3 on 2026-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_track', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('audience', models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Teachers', 'Teachers')], max_length=20)),
            ],
        ),
    ]
