# Generated by Django 5.2.3 on 2026-10-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_track', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorlog',
            name='activity',
            field=models.CharField(choices=[('Attentive', 'Attentive'), ('Irrelevant', 'Irrelevant'), ('Sleeping', 'Sleeping'), ('Using_Mobile', 'Using_Mobile')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_date'),
        ),
    ]
